---
title: Assignment 1) Forecasting temperature anomalies
output: html_notebook
---

# Initialize
```{r}
rm(list = ls());
graphics.off();
cat("\014");
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
library(dplyr)
```
# Functions for predictions
```{r}
#' Function that defines the linear trend model
f <- function(j){
  c(1,j)
}

# Functions for updating Fn to Fm
# calling F(n) updates F0 to Fn
update_F<-function(m, lambda=1, Fn=matrix(0,nrow=2,ncol=2), n=0){
  if(n>m){return(NaN)}
  if(n==m){return(Fn)}
  for (j in n:(m-1)){Fn = Fn + lambda^j*f(-j)%*%t(f(-j))}
  Fn
}

update_h<-function(m,Y, lambda=1, hn=c(0,0), n=0){
  if(n>m){return(NaN)}
  if(n==m){return(hn)}
  L=matrix(c(1,1,0,1),nrow=2)
  for (j in n:(m-1)){hn = lambda*solve(L)%*%hn + f(0)*Y[j+1]}
  c(hn) #return as vector instead of matrix
}

# Function that calculates theta_n for all n in N (N should be in increasing 
# order). Output is a 2xn matrix or a 2D vector if N is a scalar.
calculate_theta<-function(N, Y, lambda=1){
  len=length(N)
  theta=theta=matrix(0,nrow=2,ncol=len)
  
  #initialise FN and hN and calculate first theta
  #if N=1 the estimate of theta is just [Y_1, 0] -> from where??? WLS?
  hn=update_h(N[1],Y,lambda=lambda)
  Fn=update_F(N[1],lambda=lambda)
  if(N[1]==1){ theta[,1]=hn }
  else{ theta[,1] = solve(Fn,hn) }
  
  if(len==1){ return(c(theta)) }
  
  # iteratively calculations of the remaining thetas using the updating formulas
  for (i in 1:(len-1)){
    Fn=update_F(N[i+1], lambda=lambda, Fn=Fn, n=N[i])
    hn=update_h(N[i+1], Y, lambda=lambda, hn=hn, n=N[i])
    theta[,i+1]=solve(Fn,hn)}
  theta
}

#retruns a data.frame there coloumns indicate the used theta_N value, and rows
#indicates the predicting steps.
make_predictions <- function(N,Y, lambda=1,step=1){
  theta=calculate_theta(N, Y, lambda=lambda)
  f_=cbind(1,step)
  pred_=f_%*%theta
  df=data.frame(pred_, row.names=step)
  colnames(df)=N
  df
}


```

# Functions for confidence intervals
```{r}
sigma2_hat <- function(N,theta,Y,lambda,p=2,lg='local',n=5){
  if (lambda==1){
    #estimating sigma2 as σ^2 = ε^T ε/(N −p)
    y=Y[1:N]
    x=cbind(1,(-N+1):0)
    eps=y-x%*%theta #residuals using theta_N
    sigma2=diag(t(eps)%*%eps/(N-p))
  }
  else if (lg=='local'){
    #estimating sigma2 using local estimater
    y=Y[1:N]
    x=cbind(1,(-N+1):0)
    eps=y-x%*%theta #residuals using theta_N
    T_=0
    Sigma_inv=matrix(0,nrow=N,ncol=N)
    for(j in 0:(N-1)){
      T_=T_+lambda^j
      Sigma_inv[j+1,j+1]=lambda^((N-1)-j)
    }
    sigma2=c(1/(T_-p)*t(y-x%*%theta)%*%Sigma_inv%*%(y-x%*%theta))
  }
  else if (lg=='global'){
    sigma2=0
    for (j in (n+1):N){
      pred = make_predictions(j-1,Y, lambda=lambda,step=1)
      F_ = update_F(j-1, lambda=lambda)
      sigma2 = sigma2 + (Y[j]-pred)^2/(1+t(f(1)%*%solve(F_)%*%f(1)))
    }
    sigma2=sigma2/(N-n)
  }
  as.numeric(sigma2)
}


var_pred_err <- function(N,theta,Y, lambda,step,type='pred',p=2,lg='local'){
  f_ = rbind(1,step)
  FN = update_F(N,lambda=lambda)
  s2 = sigma2_hat(N,theta,Y,lambda,p=p,lg=lg)
  tmp = diag(t(f_)%*%solve(FN)%*%f_) #diag is nescesary then step is a list
  if (type=='pred'){
    var=s2*(1+tmp)
  }else if (type=='conf'){
    var=s2*(tmp)
  }
  var
}

pred_interval <- function(N,theta,Y, lambda,step, conf=0.95,type='pred',p=2,lg='local'){
  theta = calculate_theta(N,Y=data$nh, lambda=lambda)
  var = var_pred_err(N,theta,Y,lambda, step,type=type, p=p,lg=lg)
  qt((1+conf)/2,df=N-p)*sqrt(var)
}

```

# Read data
```{r}
keeps <- c('year','nh')
data <- read.table("A1_annual.txt", header = TRUE)[keeps]  %>%
  mutate(data_type = c(replicate(164, 'Training'),replicate(5, 'Test')))
head(data)
tail(data)
```

# Question 1 - data visualisation
```{r}
plot_data <- ggplot() +
      geom_point(data=data,aes(x=year, y=nh,color=data_type)) +
      geom_line(data=data,aes(x=year, y=nh),col='black') +
      labs(title="Temperature anomality for the Northern hemisphere", 
           x="year", y="Temperature",  color = "Data") +
      theme(plot.title = element_text(size = 14, face = "bold", 
            color = "darkgreen"), legend.position = "right")
ggsave(file="data.pdf", plot=plot_data , width=8, height=5)
plot_data 
```

# Question 2-3 - global and local model (lambda=1 and lambda=0.8)
```{r}
conf_type='local'
lambda=0.8 # <- change to get the corresponding plots
#global one step predictions for the test data
pred = as.numeric(make_predictions(N=1:164,Y=data$nh, lambda=lambda,step=1))  #Y_N+1|N
pred_err = data$nh[2:164]-pred[-164] #Y_N+1-Y_N+1|N (Y_165 isn't training data)
pred_int = c()
for (n in 3:164){
  pred_int=c(pred_int,pred_interval(N=n,Y=data$nh,lambda=lambda,step=1,type='pred',lg=conf_type))
}






#forecast and confintervals
forecast = make_predictions(N=164,Y=data$nh, lambda=lambda,step=1:5)$'164' #Y_N+l|N
pred_uncertainty = pred_interval(N=164,Y=data$nh,
                                 lambda=lambda,step=1:5,type='pred',lg=conf_type)
conf_uncertainty = pred_interval(N=164,Y=data$nh,
                                 lambda=lambda,step=1:5,type='conf',lg=conf_type)


plwr = forecast-pred_uncertainty
pupr = forecast+pred_uncertainty
clwr = forecast-conf_uncertainty
cupr = forecast+conf_uncertainty



#plot of one step predictions
ymin=pred[3:164]-pred_int
ymax=pred[3:164]+pred_int
plot_one_step <-  ggplot()+ 
  geom_ribbon(aes(ymin=ymin,ymax=ymax,x=data$year[4:165]), fill="blue", alpha=0.3)+
  geom_ribbon(aes(ymin=plwr,ymax=pupr,x=data$year[165:169]), fill="blue", alpha=0.3)+
  geom_line(aes(x=data$year[165:169],y=plwr),col='blue',alpha=0.5)+
  geom_line(aes(x=data$year[165:169],y=pupr),col='blue',alpha=0.5)+
  geom_line(aes(x=data$year[4:165],y=ymin),col='blue',alpha=0.5)+
  geom_line(aes(x=data$year[4:165],y=ymax),col='blue',alpha=0.5)+
  geom_point(data=data,aes(x=year, y=nh,color=data_type)) +
  geom_line(data=data,aes(x=year, y=nh),col='black') +
  geom_point(aes(x=data$year[2:165], y=pred), color='red',size=0.75)+ #size=0.2
  geom_line( aes(x=data$year[2:165], y=pred), color='red',size=0.4)+#size=0.2
  geom_point(aes(x=data$year[165:169], y=forecast), color='black',size=0.75)+#size=0.2
  geom_line( aes(x=data$year[165:169], y=forecast), color='black',size=0.4)+#size=0.2
  labs(title="Temperature anomality for the Northern hemisphere", 
           x="year", y="Temperature",  color = "Data") +
  theme(plot.title = element_text(size = 14, face = "bold", 
            color = "darkgreen"), legend.position = "right")+
  scale_color_manual(name = "Data", values = c("Test" = "#F8766D", "Training" = "turquoise", "1 step predictions"="red","1-5 step forecasts"='black'))
#ggsave(file="global.pdf", plot=plot_one_step, width=8, height=5)

#plot of one step predictions errors
plot_pred_err=ggplot()+
  geom_hline(yintercept = 0)+
  geom_point(aes(x=data$year[2:164],y=pred_err),pch=1)+
  labs(title="One step prediction errors - global Model",
       x="year", y="error")+
  theme(plot.title = element_text(size = 20,face = "bold",color = "darkgreen"))
ggsave(file=paste("resplot_lambda", lambda, ".pdf"), plot=plot_pred_err, width=10, height=6)

#plot of forecasted values
plot_forecast <- plot_one_step +
  geom_point(aes(x=data$year[165:169], y=forecast), color='black',size=0.2)+
  geom_line( aes(x=data$year[165:169], y=forecast), color='black',ize=0.2)+
  labs(title='Forecasting temperature anomality using Global Trend Model')
ggsave(file="global.pdf", plot=plot_forecast, width=8, height=5)


plot_close=plot_one_step+xlim(2000, 2018)+ylim(-0.4,1.2)
ggsave(file="global2.pdf", plot=plot_close, width=5, height=4)

plot_one_step
plot_pred_err
plot_close
```
```{r}
paste(lambda, "hej", sep = "")
```


# Question 4
Optimize for lambda
```{r}
##### optimering af lambda
prediction_error_SSE <- function(lambda,N,Y,step=1){
  pred_ = as.numeric(make_predictions(N,data$nh,lambda=lambda,step=step))
  #sum squared error
  norm(pred_-Y[N+1],type="2")
}

##### optimering af lambda
sse_err=c()
lambdas=seq(0.001,1,by=0.001)
N=6:163  #what residuals to count
for(lambda in lambdas) {
  sse_err=c(sse_err,prediction_error_SSE(lambda,N,data$nh))
}

opt=optimize(prediction_error_SSE,lower=0,upper=1,Y=data$nh,N=N)
plot_optimal_lambda <- ggplot()+
  geom_line(aes(x=lambdas,y=sse_err))+
  geom_point(aes(x=opt$min,y=opt$objective),color='red',pch=4,size=2,stroke = 2)+
  labs(title=expression(paste("Optimal Value is obtained for ", lambda, " = 0.84478")),
       x=expression(lambda), y="SSE of one step predictions")+
  theme(plot.title = element_text(size = 20,face = "bold",color = "darkgreen"))
  #geom_vline(xintercept=opt$minimum)
plot_optimal_lambda
ggsave(file="optimal.pdf", plot=plot_optimal_lambda, width=8, height=5)
```

