---
title: "R Notebook"
output: html_notebook
---

```{r}
library(marima)
library(ggplot2)

setwd("C:\\Users\\mikke\\OneDrive\\Dokumenter\\DTU documents\\8. semester (overgangssemester)\\02417 - Time Series Analysis\\Afleveringer\\Assignment 4\\Aflevering")

ds <- read.csv('A4_data.csv', sep='\t')
ds$time_step <- c(1:length(ds$yyyymm))

train <- head(ds, length(ds$yyyymm)-4)
val <- tail(ds, 4)

head(ds)
```

```{r}
ar_degree <- 1
ma_degree <- 7

Model1 <- define.model(kvar=10, rem.var=c(1,7:10), indep=NULL, reg.var=NULL, ma=c(1:ma_degree))
Marima <- marima(train, means=1, ar.pattern=Model1$ar.pattern, ma.pattern=Model1$ma.pattern, Plot="log.det", Check=FALSE, penalty=1)
Marima
```
```{r}
nstep = 4
val_empty <- val
val_empty$Cnsmr <- rep(0,nstep)
val_empty$Manuf <- rep(0,nstep)
val_empty$HiTec <- rep(0,nstep)
val_empty$Hlth  <- rep(0,nstep)
val_empty$Other <- rep(0,nstep)
forecast_df <- rbind(train, val_empty)

Forecasts <- arma.forecast(series = forecast_df, marima = Marima, nstart = length(train$yyyymm), nstep = nstep)

forecast_df <- data.frame(
  yyyymm <- ds$yyyymm,
  Cnsmr <- Forecasts$forecasts[2,],
  Manuf <- Forecasts$forecasts[3,],
  HiTec <- Forecasts$forecasts[4,],
  Hlth <- Forecasts$forecasts[5,],
  Other <- Forecasts$forecasts[6,],
  b.m <- ds$b.m,
  ntis <- ds$ntis,
  infl <- ds$infl,
  time_step <- ds$time_step
)
```

```{r}
p2 <- ggplot(ds, aes(time_step, Cnsmr)) +     # Scatter plot
    geom_point(color="black") +
    geom_line(data=forecast_df, aes(time_step, Cnsmr), color="blue")
    
p2
```

