---
title: "Assignment 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
library(tidyverse)
library(stats)
```



# Q4.1: Presenting data

```{r}
data <- read.csv("A4_data.csv", sep = "\t") %>% 
  mutate(date = as.Date(yyyymm %>% 
                          as.character() %>% 
                          paste0("01"), 
                        format = "%Y%m%d"))  %>% 
  select(-yyyymm)
summary(data)
head(data)
```

```{r}
max(data$date)
```



```{r}
# pdf("Industries.pdf", width = 5, height = 7.5)

plot_data <- data %>% 
  # mutate('Total industry' = select(., Cnsmr,Manuf,HiTec,Hlth,Other) %>% sum()) %>% 
  rename(Consumer = Cnsmr, Manufacturing = Manuf, "High tech" = HiTec, Healthcare = Hlth) %>% 
  gather(Industry, "Monthly return", Consumer, Manufacturing, "High tech", Healthcare, Other) %>% #, "Total industry") %>% 
  mutate(row = ifelse(Industry %in% c('Consumer', 'Manufacturing', "High tech"), 1, 2))
  
  gridExtra::grid.arrange(
    ggplot(plot_data %>% filter(Industry %in% c('Consumer', 'Manufacturing', "High tech"))) +
      geom_line(aes(x = date, y = `Monthly return`)) +
      facet_grid(cols = vars(Industry), scale = "free_y"),
    
    ggplot(plot_data%>% filter(!(Industry %in% c('Consumer', 'Manufacturing', "High tech")))) +
      geom_line(aes(x = date, y = `Monthly return`)) +
      facet_grid(cols = vars(Industry), scale = "free_y"),
    
    nrow = 2
  )
  

# dev.off()
```

```{r}
plot_data %>% ggplot() +
  geom_point(aes(date, `Monthly return`, color = Industry, shape = Industry), size = 1)

plot_data %>% ggplot() +
  geom_line(aes(date, `Monthly return`, color = Industry), alpha = .5) +
  ylim(-20, 20)
```



```{r}
gridExtra::grid.arrange(
    ggplot(data) +
      geom_line(aes(x = date, y = b.m)) +
      ylab("Book to market ratio"),
    
    ggplot(data) +
      geom_line(aes(x = date, y = ntis)) +
      ylab("Net equity expansion"),
    
    ggplot(data) +
      geom_line(aes(x = date, y = infl)) +
      ylab("Inflation"),
    
    nrow = 3
)
```


# Q4.2: ACF, PACF and CCF

of the returns from the five industries


```{r echo=FALSE, fig.height=30, fig.width=, warning=FALSE}

#ACF and PACF

layout(matrix(c(1,1,2,3,4,4,5,6,7,7,8,9,10,10,11,12,13, 13, 14, 15), nrow = 10, byrow = TRUE), heights=c(1,3,1,3,1,3,1,3,1,3))
plot.new()
text(0.5,0.5,"Consumer",cex=3,font=2)
acf(data$Cnsmr, main=NA, lag.max=60)
pacf(data$Cnsmr, main=NA,  lag.max=60)
plot.new()
text(0.5,0.5,"Manufactoring",cex=3,font=2)
acf(data$Manuf, main=NA, lag.max=60)
pacf(data$Manuf, main=NA,  lag.max=60)
plot.new()
text(0.5,0.5,"High tech",cex=3,font=2)
acf(data$HiTec, main=NA, lag.max=60)
pacf(data$HiTec, main=NA,  lag.max=60)
plot.new()
text(0.5,0.5,"Healthcare",cex=3,font=2)
acf(data$Hlth, main=NA, lag.max=60)
pacf(data$Hlth, main=NA,  lag.max=60)
plot.new()
text(0.5,0.5,"Other",cex=3,font=2)
acf(data$Other, main=NA, lag.max=60)
pacf(data$Other, main=NA,  lag.max=60)

```



```{r, echo=FALSE,warning = FALSE, fig.height = 35 fig.width = 30}

##CCF

layout(matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), nrow = 6, byrow = TRUE), heights=c(1,3,1,3,1,3))
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
ccf(data$Cnsmr,data$Manuf, main = NA, lag.max = 16)
ccf(data$Cnsmr,data$HiTec, main = NA, lag.max = 16)
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
ccf(data$Cnsmr,data$Hlth, main = NA, lag.max = 16)
ccf(data$Cnsmr,data$Other, main = NA, lag.max = 16)
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
plot.new()
text(0.5,0.5,"CCF z2000, z2800",cex=3,font=2)
ccf(data$Manuf,data$HiTec, main = NA, lag.max = 16)
ccf(data$Manuf,data$Hlth, main = NA, lag.max = 16)

```



#Måske der lige skal applies noget differencing. Look into this and plot ACF and PACF for the differenced data. 



```{r}

ccf(data$Cnsmr,data$Manuf, main = NA)

```


```{r, echo=FALSE,warning = FALSE, fig.height = 45 fig.width = 40}

##CCF

layout(matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), nrow = 6, byrow = TRUE), heights=c(1,4,1,4,1,4))
plot.new()
text(1,1,"CCF Consumer, Manufacturing",cex=2,font=1)
plot.new()
text(1,1,"CCF Consumer, Hightech",cex=2,font=1)
ccf(data$Cnsmr,data$Manuf, main = NA)
ccf(data$Cnsmr,data$HiTec, main = NA)
plot.new()
text(1,1,"CCF Consumer, Healthcare",cex=2,font=1)
plot.new()
text(1,1,"CCF Consumer, Other",cex=2,font=1)
ccf(data$Cnsmr,data$Hlth, main = NA)
ccf(data$Cnsmr,data$Other, main = NA)
plot.new()
text(1,1,"CCF Manufacturing, Hightech",cex=2,font=1)
plot.new()
text(1,1,"CCF Manufacturing, Healthcare",cex=2,font=1)
ccf(data$Manuf,data$HiTec, main = NA)
ccf(data$Manuf,data$Hlth, main = NA)

```

#...





