---
title: "MARIMA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
library(tidyverse)
library(stats)
library(marima)
```


```{r}
data <- read.csv("A4_data.csv", sep = "\t") %>% 
  mutate(date = as.Date(yyyymm %>% 
                          as.character() %>% 
                          paste0("01"), 
                        format = "%Y%m%d"))  %>% 
  select(-yyyymm)
summary(data)
head(data)
```
```{r}
N_cols <- dim(data)[2]
N
ncol(data)
```





```{r}
marima_data <- data %>% select(-date)
N <- ncol(marima_data)
Model1 <- define.model(kvar=N, rem.var=c(6:N), indep=NULL, reg.var=NULL, ar=c(1:3), ma = c(1:3)) # , ar=c(1), ma=c(1:2)
Marima1 <- marima(t(marima_data), means=1, ar.pattern=Model1$ar.pattern, ma.pattern=Model1$ma.pattern, Plot="log.det", Check=FALSE, penalty=0)
Marima1
```

```{r}
source("step.slow.marima_2017.R")
source("step.slow.p.marima_2017.R")


Marima2 <- step.slow.p(Marima1, data=t(marima_data))
```


```{r}
Marima2
```

