---
title: "R Notebook"
output: html_notebook
---

```{r}
library(marima)
library(ggplot2)
require(forecast)
library(magrittr)
library(tidyverse)
library(stats)

#setwd('/Users/joergensen/Documents/DTU_Mat_Tek/4.semester/02417_TimeSeriesAnalysis/Asignment4')

data <- read.csv('A4_data.csv', sep='\t')%>% 
            mutate(date = as.Date(yyyymm %>% 
                          as.character() %>% 
                          paste0("01"), 
                          format = "%Y%m%d"))  %>% 
            select(-yyyymm)

n_test = 4
N = length(data$date)
n_train = N-n_test

#exclude time
train <- head(data[,1:8], n_train)
val <- tail(data[,1:8], n_test)

head(data)
```

```{r}
ar_degree <- 5
ma_degree <-5

#Model1 <- define.model(kvar=8, rem.var=c(6:8), indep=NULL, reg.var=NULL, ma=c(1:ma_degree), ar=c(1:ar_degree))
Model1 <- define.model(kvar=8, rem.var=NULL, indep=NULL, reg.var=c(6:8), ma=c(1:ma_degree), ar=c(1:ar_degree))
Marima <- marima(train, means=1, ar.pattern=Model1$ar.pattern, ma.pattern=Model1$ma.pattern, Plot="log.det", Check=FALSE, penalty=1)
Marima
```


```{r}
#Check residuals

#Marima$residuals
qqnorm(Marima$residuals, pch = 1, frame = FALSE)
qqline(Marima$residuals, col = "steelblue", lwd = 2)




```
```{r}
library(forecast)
resdf <- Marima$residuals
#check.residuals(resdf[1,])
checkresiduals(resdf[1,])


```





```{r}
ar_degree <- 3
ma_degree <-3

#Model1 <- define.model(kvar=8, rem.var=c(6:8), indep=NULL, reg.var=NULL, ma=c(1:ma_degree), ar=c(1:ar_degree))
Model2 <- define.model(kvar=8, rem.var=NULL, indep=NULL, reg.var=c(6:8), ma=c(1:ma_degree), ar=c(1:ar_degree))
Marima2 <- marima(train, means=1, ar.pattern=Model2$ar.pattern, ma.pattern=Model2$ma.pattern, Plot="log.det", Check=FALSE, penalty=1)
Marima2
```
```{r}
#Marima$residuals
qqnorm(Marima2$residuals, pch = 1, frame = FALSE)
qqline(Marima2$residuals, col = "steelblue", lwd = 2)


```


```{r}

library(forecast)
resdf <- Marima2$residuals
#check.residuals(resdf[1,])
checkresiduals(resdf[1,])


```






```{r}
#estimates and coefficients

round(short.form(Marima$ar.fvalues,leading=FALSE),4)

```



```{r}

round(short.form(Marima$ma.pvalues,leading=FALSE),4)


```




```{r}
nstep = n_test
forecast_df=rbind(train, val)
forecast_df[(N-3):N,1:5] = 0

Forecasts = arma.forecast(series = forecast_df, marima=Marima, nstart = n_train, nstep = nstep)

#overwrite forecast_df with forcasted values
forecast_df[,1:5]=t(Forecasts$forecasts[1:5,])

```


```{r}
source("/Users/gabriellakierulff/Desktop/HCAI/Time Series Analysis/Exercises/step.slow.p.marima_2017.R")


slp <- step.slow.p(Marima, data, p.value = 0.05)

short.form(slp$ar.estimates, leading=FALSE) # print estimates
short.form(slp$ma.estimates, leading=FALSE)
```



```{r}

industri = "Cnsmr"
idx = which(colnames(train)==industri)

varians = Forecasts$pred.var
var = rep(diag(varians[,,1])[idx], n_train)
for (i in 1:4) {var = c(var, diag(varians[,,i])[idx])}

df = data.frame(
  time = data$date,
  data = data[industri],
  pred = forecast_df[industri],
  lower = forecast_df[industri]-1.96*sqrt(var),
  upper = forecast_df[industri]+1.96*sqrt(var)
)
colnames(df)=c('time','data','pred','lower','upper')
df_train = head(df,n_train)
df_test = tail(df,n_test)

plot_Cnsmr <- ggplot() +     # Scatter plot
      geom_ribbon(data=df_train, aes(x=time,ymin=lower,ymax=upper), fill="blue", alpha=0.5)+
      geom_ribbon(data=df_test, aes(x=time,ymin=lower,ymax=upper), fill="red", alpha=0.5)+
    geom_line(data=df, aes(time, data))+ 
    geom_line(data = df_train,aes(time, pred), color="blue")+
    geom_line(data = df_test,aes(time, pred), color="red")+
    labs(title=paste('Predictions for ',industri))



plot_Cnsmr

plot_Cnsmr+xlim(data$date[N-100],data$date[N])

```
```{r}
qqnorm(Forecasts$resid, pch = 1, frame = FALSE)
qqline(Forecasts$resid, col = "steelblue", lwd = 2)

```



```{r}

qqnorm(Forecasts$resid, pch = 1, frame = FALSE)
qqline(Forecasts$resid, col = "steelblue", lwd = 2)


```

```{r}
library(forecast)
resdf <- Forecasts$residuals
checkresiduals(resdf[1,])



```



