---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(magrittr)
library(tidyverse)
library(marima)
```

# Read data

```{r}
# setwd("/Users/joergensen/Documents/DTU_Mat_Tek/4.semester/02417_TimeSeriesAnalysis/Assignment_3_Laws")
data <- read.csv(file = 'DataAssignment3.csv')
parti_color=data$Government
parti_color[data$Government=="Social Democrats"]='#b02424'
parti_color[data$Government=="Venstre"]='#304c74'
parti_color[data$Government=="Conservative"]='#90a424'
parti_color[data$Government=="Social Liberals"]='green'
parti_color[data$Government=="Independent"]='yellow'
head(data)
```



## Plot data

```{r}
(plot <- ggplot(data = data)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_line(aes(x=Date,y=NumberWords)))

# plot

```


## Transform data

```{r}
diff_order <- 2

data <- data %>%
  mutate(NumberWordsTrans = data %>% .$NumberWords %>% log() %>%  diff(differences = diff_order) %>% c(rep(NA, diff_order), .)) %>% 
  # caret::dummyVars()
  mutate(Conservative = ifelse(Government == "Conservative", 1,0)) %>% #replace(TRUE, 1) %>% replace(FALSE, 0)) %>%
  mutate(Independent = ifelse(Government == "Independent", 1,0)) %>%
  mutate("Social Democrats" = ifelse(Government == "Social Democrats", 1,0)) %>%
  mutate("Social Liberals" = ifelse(Government == "Social Liberals", 1,0)) %>%
  mutate("Venstre" = ifelse(Government == "Venstre", 1,0))
data


```

## Plot transformed data

```{r}
(plot <- ggplot(data = data)+
  geom_point(aes(x=Date,y=NumberWordsTrans))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWordsTrans))+
  geom_line(aes(x=Date,y=NumberWordsTrans)))
```




# ARIMA

```{r}
data %>% .$NumberWordsTrans %>% arima(c(0,0,1))
```



# MARIMA

```{r}
model <- marima::define.model(kvar = ncol(data), ar=0, ma=1, rem.var=c(1:3), reg.var = c(5:9), indep=NULL)
marima::marima(t(data), ar.pattern=model$ar.pattern, ma.pattern=model$ma.pattern)
```

## Own differencing

```{r}
ar = c(1)
ma = c(1)
data2 <- data[, c(1:2, 4:9)]
# data2[2:6] %>% diff(differences = 2)
model <- marima::define.model(kvar = ncol(data2), rem.var = c(1,2), ma=ma, ar = ar, reg.var = c(4:9))
marima_model <- marima::marima(t(data2), ar.pattern=model$ar.pattern, ma.pattern=model$ma.pattern, Plot="log.det", penalty=0)

# marima_model
print("MA params:")
marima::short.form(marima_model$ma.estimates, leading = F)
print("MA p-values")
marima_model$ma.pvalues
print("AR params:")
marima::short.form(marima_model$ar.estimates, leading = F)
print("AR p-values")
marima_model$ar.pvalues


```

```{r}
(plot <- ggplot(data = data)+
  geom_point(aes(x=Date,y=NumberWordsTrans))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWordsTrans))+
  geom_line(aes(x=Date,y=NumberWordsTrans))) +
  geom_point(aes(x = Date, y = c(NA, NA, marima_model$residuals[8,]), color = "red"))
```





```{r}
forecasts <- arma.forecast(data2, nstart=12, nstep=90, marima=marima_model, check = F)
```
### Forecasting

```{r} 
forecast_invtrans <- forecasts$forecasts[3,] %>% diffinv(differences = 2, xi = log(data2$NumberWords[1:2])) %>% exp()
(plot <- ggplot(data = data)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_line(aes(x=Date,y=NumberWords)) +
  geom_point(aes(x = Date, y = forecast_invtrans[1:102]), shape = 2)
  )

```

```{r}
stdv <- sqrt(forecasts$pred.var[8,8,]) *1.96
forecasts$forecasts[3,] 
- cbind(0,stdv) %>% diffinv(differences = 2, xi = log(data2$NumberWords[1:2])) %>% exp()
```

```{r}
data4 <- data2 %>% 
  mutate("forecast" = arma.forecast(data2, nstart=12, nstep=90, marima=marima_model, check = F)$forecasts[3,] ) %>% 
  mutate("forecast_inv_trans" = 
           forecast %>% 
           diffinv(differences = 2, xi = log(data2$NumberWords[1:2])) %>% 
           exp() %>% .[1:102]) %>% 
  mutate(pred_var = c(rep(0, 12), forecasts$pred.var[8,8,])) %>% 
  mutate("forecast_inv_trans_lower" = 
           (forecast - sqrt(pred_var)*1.96) %>% 
           diffinv(differences = 2, xi = log(data2$NumberWords[1:2])) %>% 
           exp() %>% .[1:102]) %>% 
  mutate("forecast_inv_trans_upper" = 
           (forecast + sqrt(pred_var)*1.96) %>% 
           diffinv(differences = 2, xi = log(data2$NumberWords[1:2])) %>% 
           exp() %>% .[1:102]) %>% 
  mutate("residuals" = NumberWords-forecast_inv_trans)
```
```{r}
(plot <- ggplot(data = data4)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_line(aes(x=Date,y=NumberWords)) +
  geom_point(aes(x = Date, y = forecast_inv_trans), shape = 2)
  # geom_point(aes(x = Date, y = forecast_inv_trans_lower), shape = 2) +
  # geom_point(aes(x = Date, y = forecast_inv_trans_upper), shape = 2)
  )
```
```{r}
data4 %>% 
  ggplot() %>% 
  geom_point(aes(x=Date, ))
```



## Differencing with define.dif


```{r}
data3 <- data2[-3]
data3["log_data"] <- log(data3$NumberWords)
# differences <- rbind(c(1:8), c(0,1,0,0,0,0,0,1))
differences <- matrix(c(8,1,8,1), nrow = 2)
dy <- define.dif(t(data3), differences)

ar <- c(1)
ma = c(1)
model2 <- define.model(kvar = ncol(data3), rem.var = c(1,2), ma=ma, ar = ar, reg.var = c(3:7))
marima_model2 <- marima(t(data2), ar.pattern=model2$ar.pattern, ma.pattern=model2$ma.pattern, Plot="log.det", penalty=.5)

# marima_model
print("MA params:")
short.form(marima_model2$ma.estimates, leading = F)
print("MA p-values")
marima_model2$ma.pvalues
print("AR params:")
short.form(marima_model2$ar.estimates, leading = F)
print("AR p-values")
marima_model2$ar.pvalues

```



### Forecasting


```{r}
Forecasts <- arma.forecast(t(data3), marima = marima_model2, nstart = 12, nstep = 90, dif.poly = dy$dif.poly)
```

```{r}
(plot <- ggplot(data = data)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_rect(data=data,aes(xmin = Date, xmax = Date+1,
                 ymin = -Inf, ymax = Inf,fill=Government),alpha=0.55)+
  geom_point(aes(x=Date,y=NumberWords))+
  geom_line(aes(x=Date,y=NumberWords)) +
  geom_point(aes(x = Date, y = Forecast$forecasts[8,] %>% exp()), shape = 2)
  )
```

```{r}
Forecast$forecasts[8,] %>% exp()
```

